export const FETCH_LEAGUES_BEGIN = 'FETCH_LEAGUES';
export const FETCH_LEAGUES_SUCCESS = 'FETCH_LEAGUES_SUCCESS';
export const FETCH_LEAGUES_ERROR = 'FETCH_LEAGUES_ERROR';
export const SELECT_LEAGUE = 'SELECT_LEAGUE';

export const FETCH_SEASONS_BEGIN = 'FETCH_SEASONS_BEGIN';
export const FETCH_SEASONS_SUCCESS = 'FETCH_SEASONS_SUCCESS';
export const FETCH_SEASONS_ERROR = 'FETCH_SEASONS_ERROR';