export const FETCH_LEAGUES_BEGIN = 'FETCH_LEAGUES';
export const FETCH_LEAGUES_SUCCESS = 'FETCH_LEAGUES_SUCCESS';
export const FETCH_LEAGUES_ERROR = 'FETCH_LEAGUES_ERROR';
export const SELECT_LEAGUE = 'SELECT_LEAGUE';

export const FETCH_SEASONS_BEGIN = 'FETCH_SEASONS_BEGIN';
export const FETCH_SEASONS_SUCCESS = 'FETCH_SEASONS_SUCCESS';
export const FETCH_SEASONS_ERROR = 'FETCH_SEASONS_ERROR';
export const SELECT_SEASON = 'SELECT_SEASON';

export const FETCH_LEAGUE_TABLE_BEGIN = 'FETCH_LEAGUE_TABLE_BEGIN';
export const FETCH_LEAGUE_TABLE_SUCCESS = 'FETCH_LEAGUE_TABLE_SUCCESS';
export const FETCH_LEAGUE_TABLE_ERROR = 'FETCH_LEAGUE_TABLE_ERROR';
export const SELECT_STAGE = 'SELECT_STAGE';