export const FETCH_LEAGUES_BEGIN = "FETCH_LEAGUES";
export const FETCH_LEAGUES_SUCCESS = "FETCH_LEAGUES_SUCCESS";
export const FETCH_LEAGUES_ERROR = "FETCH_LEAGUES_ERROR";
export const SELECT_LEAGUE = "SELECT_LEAGUE";

export const FETCH_SEASONS_BEGIN = "FETCH_SEASONS_BEGIN";
export const FETCH_SEASONS_SUCCESS = "FETCH_SEASONS_SUCCESS";
export const FETCH_SEASONS_ERROR = "FETCH_SEASONS_ERROR";
export const SELECT_SEASON = "SELECT_SEASON";

export const FETCH_LEAGUE_TABLE_BEGIN = "FETCH_LEAGUE_TABLE_BEGIN";
export const FETCH_LEAGUE_TABLE_SUCCESS = "FETCH_LEAGUE_TABLE_SUCCESS";
export const FETCH_LEAGUE_TABLE_ERROR = "FETCH_LEAGUE_TABLE_ERROR";
export const FETCH_TOP_SCORERS_BEGIN = "FETCH_TOP_SCORERS_TABLE_BEGIN";
export const FETCH_TOP_SCORERS_SUCCESS = "FETCH_TOP_SCORERS_SUCCESS";
export const FETCH_TOP_SCORERS_ERROR = "FETCH_TOP_SCORERS_ERROR";
export const SELECT_STAGE = "SELECT_STAGE";
export const SELECT_TOP_SCORER_PLAYER = "SELECT_TOP_SCORER_PLAYER";
export const FETCH_TOP_SCORER_PLAYER_BEGIN = "FETCH_TOP_SCORER_PLAYER_BEGIN";
export const FETCH_TOP_SCORER_PLAYER_SUCCESS =
  "FETCH_TOP_SCORER_PLAYER_SUCCESS";
export const FETCH_TOP_SCORER_PLAYER_ERROR = "FETCH_TOP_SCORER_PLAYER_ERROR";

export const SELECT_TEAM = "SELECT_TEAM";
export const SELECT_PLAYER = "SELECT_PLAYER";
export const FETCH_TEAM_BEGIN = "FETCH_TEAM_BEGIN";
export const FETCH_TEAM_SUCCESS = "FETCH_TEAM_SUCCESS";
export const FETCH_TEAM_ERROR = "FETCH_TEAM_ERROR";
export const FETCH_TEAM_PLAYERS_BEGIN = "FETCH_TEAM_PLAYERS_BEGIN";
export const FETCH_TEAM_PLAYERS_SUCCESS = "FETCH_TEAM_PLAYERS_SUCCESS";
export const FETCH_TEAM_PLAYERS_ERROR = "FETCH_TEAM_PLAYERS_ERROR";
